version: '3.8'

services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
    networks:
      - backend

  pgdb:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_INITDB_ARGS="--encoding=UTF8"
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    networks:
      - backend

volumes:
  pgdbdata: null

networks:
  backend:
