# Generated by Django 3.2.25 on 2024-06-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balances', '0002_auto_20240609_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbalance',
            name='reserved_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
